[global]
api_key = "han1234"
admin_username = "admin"
admin_password = "admin"

[flow]
labs_base_url = "https://labs.google/fx/api"
api_base_url = "https://aisandbox-pa.googleapis.com/v1"
timeout = 120
poll_interval = 3.0
max_poll_attempts = 200

[server]
host = "0.0.0.0"
port = 8000

[debug]
enabled = false
log_requests = true
log_responses = true
mask_token = true

[proxy]
proxy_enabled = false
proxy_url = ""

[generation]
image_timeout = 300
video_timeout = 1500

[admin]
error_ban_threshold = 3

[cache]
enabled = false
timeout = 7200  # 缓存超时时间(秒), 默认2小时
base_url = ""   # 缓存文件访问的基础URL, 留空则使用服务器地址

[captcha]
captcha_method = "browser"  # 打码方式: yescaptcha/capmonster/ezcaptcha/capsolver/flow_service/browser/personal
yescaptcha_api_key = ""  # YesCaptcha API密钥
yescaptcha_base_url = "https://api.yescaptcha.com"
flow_captcha_service_base_url = "http://223.167.72.194:35201"
flow_captcha_service_solve_path = "/api/v1/captcha/solve"
flow_captcha_service_api_key = ""
flow_captcha_service_timeout_seconds = 120
